import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/header"
import Form from "@/components/searchForm/form/formCity";
import Script from 'next/script'
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fr" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col p-2 h-screen  `}
      >
        <header>
          <Header></Header>
        </header>
        <div className="mt-[1em]  flex justify-center">
          <Form type={"city"}></Form>
        </div>
        <div className=" flex flex-col flex-1 pt-10">
          {children}
        </div>
        <footer>
          <div className="">
            <p>font : bye bye binary</p>
          </div>
        </footer>
        <Script src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_API}&libraries=places`} strategy="afterInteractive"/>
      </body>
    </html>
  );
}
